### ISSUE TITLE
start selfvis.py gets TypeError.

### ISSUE THREAD

**Issue by RezoChiang** [temporaer/selfspy-vis#1]
I install selfspy-vis with yaourt and execute with the following command:
`python2.7 /usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py --human-readable --pactive --back 8 h`
but get the error response like this
```
python2.7 /usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py --human-readable --pactive --back 8 h                                                                                                                                            
keyring library not found
Password:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py", line 767, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py", line 755, in main
    args['password'] = get_password(verify=check_with_encrypter)
  File "/usr/lib/python2.7/site-packages/selfspy/password_dialog.py", line 32, in get_password
    pw = get_user_password(verify, message)
  File "/usr/lib/python2.7/site-packages/selfspy/password_dialog.py", line 39, in get_user_password
    pw = get_tty_password(verify, message, force_save)
  File "/usr/lib/python2.7/site-packages/selfspy/password_dialog.py", line 84, in get_tty_password
    if (not verify) or verify(pw):
  File "/usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py", line 748, in check_with_encrypter
    encrypter = make_encrypter(password)
  File "/usr/lib/python2.7/site-packages/selfspy-vis/selfvis.py", line 734, in make_encrypter
    encrypter = Blowfish.new(hashlib.md5(password).digest())
TypeError: new() takes at least 2 arguments (1 given)
```
Can someone help?

**Comment by RezoChiang** [comment]
OK.  reloved this by changed selfvis.py line  734
        encrypter = Blowfish.new(hashlib.md5(password).digest())
to
        encrypter = Blowfish.new(hashlib.md5(password).digest(), Blowfish.MODE_ECB)
according to __init__.py of  selfspy.  should I push a pr for it?

**Comment by temporaer** [comment]
yes please!
